# Generated by Django 4.0.4 on 2022-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
