# Generated by Django 4.0.4 on 2022-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('beginDate', models.DateField()),
                ('endDate', models.DateField()),
                ('discountPercentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
