# Generated by Django 4.0.4 on 2022-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('salesperson', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('salesDate', models.DateField()),
            ],
        ),
    ]
