# Generated by Django 4.0.4 on 2022-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='salesDate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='salespersonCommission',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
